### ISSUE TITLE
NullPointerExceptions

### ISSUE THREAD

**Issue by IanWONeill** [chadalen/rs2cl#1]
I seem to get thrown the error for every tool other than Map and Model Dumping. Using Clean 317, modified 317, Astraeus Client cache also.

Example:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.rs2cl.Store.createArchives(Store.java:174)
	at org.rs2cl.Store.<init>(Store.java:153)
	at org.rs2cl.Cache.getArchive(Cache.java:278)
	at org.rs2cl.parser.ItemDefinitionParser.parse(ItemDefinitionParser.java:42)
	at org.rs2cl.tools.Test.main(Test.java:15)
Caused by: java.lang.NullPointerException
	at org.rs2cl.Archive.<clinit>(Archive.java:57)
	... 5 more

**Comment by chadalen** [comment]
@IanWONeill This is because when you import the project from GitHub the resources folder doesn't import as resources it imports as a regular folder.

http://i.imgur.com/iktjLqW.png

To fix this right click the project -> build path -> configure build path -> libraries tab -> add class folder -> select resources folder then hit ok

**Comment by IanWONeill** [comment]
Perfect thanks.
