### ISSUE TITLE
NpcDefinitionDumper

### ISSUE THREAD

**Issue by IanWONeill** [chadalen/rs2cl#3]
...
Unrecognised opcode=228
Unrecognised opcode=82
Unrecognised opcode=8
Unrecognised opcode=82
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
	at org.rs2cl.parser.NpcDefinitionParser.decode(NpcDefinitionParser.java:117)
	at org.rs2cl.parser.NpcDefinitionParser.parse(NpcDefinitionParser.java:74)
	at org.rs2cl.tools.NpcDefinitionDumper.main(NpcDefinitionDumper.java:45)

**Comment by chadalen** [comment]
@IanWONeill RS2CL only supports 317 iirc. If you have a modified cache where someone changed the format it's not going to read it.

That goes for all config files, I haven't added multi-support because people nowadays are making their own formats.
